name: continuous-integration

on: push

jobs:

  check-requirements:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dm-script dependencies
      run: pip install packaging==20.3 click~=7.0 pyyaml~=5.1 toml

    - name: Check requirements files
      run: python ./utils/dependency_management.py check-requirements

    - name: Create commit comment
      if: failure()
      uses: peter-evans/commit-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: setup.json
        body: |
          I have checked the requirements for this commit and found some
          inconsistencies. It appears that at least one of the environments
          used for testing (to be found in the requirements/ directory) is
          not meeting the dependencies specified in the 'setup.json' file.

          You might need to run the 'update-requirements' workflow to
          mitigate that.
